config/routes.rb
Bernergarde::Application.routes.draw do
  root :to => 'pages#show', :id => 'home', :format => 'html'

  pages = %w(
    home faq repository repository_p2 trustees operators submit donations
    studies studies_mh studies_broad_institute studies_dm studies_santera
    studies_optigen_pra studies_utrecht_liver_shunt studies_carc
    articles links
  )

  match "/:locale", :to => 'pages#show', :id => 'home', :format => 'html', :via => 'get'
  match "/:locale/:id.:format",
    :id  => /#{pages.join('|')}/,
    :to  => 'pages#show',
    :as  => 'page',
    :via => 'get'

  match "/:locale/db", :to => 'database#index', :as => 'database', :format => 'html', :via => 'get'
  scope "/:locale/db" do
    resources :people, :litters, :dogs, :vets, :reports, :photos do
      collection do
        post :search
      end
    end
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  include AnyMatcher

  has_many :dogs,             :foreign_key => 'owner_id'
  has_many :litters,          :foreign_key => 'breeder_id'
  has_many :club_memberships, :foreign_key => 'member_id'
  has_many :clubs,            :through => :club_memberships

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/people_controller.rb
class PeopleController < DatabaseController
  def index
  end

  def search
    return redirect_to people_path unless params[:bg_id].present? || params[:person].present?

    @people = params[:bg_id].present?? Person.where(:id => params[:bg_id]) : Person.matching_any(params[:person])
    if @people.empty?
      flash[:error] = t('db.search.people.no_results')
      redirect_to people_path
    elsif @people.size == 1
      redirect_to @people.first
    end
  end

  def show
    begin
      @person = Person.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to :action => :index
    end
  end
end

app/views/people/index.html.haml
%h2= t('db.search.people.header')

%p.instructions= t('db.search.people.instructions')

%p.help
  %a{:href => '#'}
    %span= t('db.search.people.help')

.search_form
  =form_tag(search_people_path(I18n.locale)) do
    %fieldset
      =label_tag('person[last_name]', t('db.search.people.last_name'))
      =text_field_tag('person[last_name]')
      =radio_button_tag('person[last_name_match]', 'begins', true)
      %span= t('db.search.begins_with')
      =radio_button_tag('person[last_name_match]', 'begins', false)
      %span= t('db.search.contains')

      %p= t('db.search.and')

      =label_tag('person[first_name]', t('db.search.people.first_name'))
      =text_field_tag('person[first_name]')
      =radio_button_tag('person[first_name_match]', 'begins', true)
      %span= t('db.search.begins_with')
      =radio_button_tag('person[first_name_match]', 'begins', false)
      %span= t('db.search.contains')

      %p= t('db.search.and')

      =label_tag('person[state]', t('db.search.people.state'))
      =select_tag('person[state]', options_for_select(state_options))

      %p= t('db.search.and')

      =label_tag('person[country]', t('db.search.people.country'))
      =select_tag('person[country]', options_for_select(country_options))

    %p= t('db.search.people.bgid_prompt')

    %fieldset
      =label_tag('bg_id', t('db.search.people.bgid'))
      =text_field_tag('bg_id')

    =submit_tag t('db.search.people.submit')

app/views/people/search.html.haml
%h1 Berner People

This will contain search results soon

app/views/people/search_results.html.haml
%h1 Berner People

This will contain search results soon

app/views/people/show.html.haml
%h2= t('db.people.header')

%dl.overview<
  %dt.name>=             t('db.people.name')
  %dd>=                  @person.full_name.upcase
  %dt.bg_id>=            t('db.people.bg_id')
  %dd>=                  @person.id
  %dt.second_name>=      t('db.people.second_name')
  %dd>
  %dt.country>=          t('db.people.country')
  %dd>=                  t("db.country.#{@person.country.downcase}")
  %dt.address>=          t('db.people.address')
  %dd>=                  @person.address.to_s.upcase
  %dt.address2>=         t('db.people.address2')
  %dd>=                  @person.address2.to_s.upcase
  %dt.city_state_zip>=   t('db.people.city_state_zip')
  %dd>=                  "#{@person.city.upcase}, #{@person.state.upcase} #{@person.zip.upcase}"
  %dt.phone>=            t('db.people.phone')
  %dd>=                  @person.phone
  %dt.email>=            t('db.people.email')
  %dd>=                  @person.email
  %dt.web_site>=         t('db.people.web_site')
  %dd>=                  @person.web_site
  %dt.fax>=              t('db.people.fax')
  %dd>=                  @person.fax
  %dt.kennel_name>=      t('db.people.kennel_name')
  %dd>=                  @person.kennel_name
  %dt.deceased>=         t('db.people.deceased')
  %dd>=                  @person.deceased
  %dt.bmdca_status>=     t('db.people.bmdca_status')
  %dd>=                  bmdca_membership_status(@person)
  %dt.display>=          t('db.people.display.label')
  %dd>=                  @person.display_contact_info?? t('db.people.display.all') : t('db.people.display.none')
  %dt.master_household>= t('db.people.master_household')
  %dd>=                  @person.master_household?? t('yes') : t('no')
  %dt.data_source>=      t('db.people.data_source')
  %dd>=                  @person.data_source
  %dt.last_updated>=     t('db.people.last_updated')
  %dd>=                  l(@person.updated_at, :format => :db)

.nav
  %ul
    %li{:class => 'subsection_nav'}>= link_to t('db.people.nav.dogs'),      '#dogs'
    %li{:class => 'subsection_nav'}>= link_to t('db.people.nav.litters'),   '#litters'
    %li{:class => 'subsection_nav'}>= link_to t('db.people.nav.clubs'),     '#clubs'
    %li{:class => 'subsection_nav'}>= link_to t('db.people.nav.household'), '#household'

%a{:name => 'dogs'}
#dogs.subsection
  %h3= t('db.people.dogs.header')
  %table
    %tr
      %th= t('db.people.dogs.bg_id')
      %th= t('db.people.dogs.registered_name')
      %th= t('db.people.dogs.call_name')
      %th= t('db.people.dogs.sex')
      %th= t('db.people.dogs.registration')
      %th= t('db.people.dogs.whelp_date')
      %th= t('db.people.dogs.reside')
      %th= t('db.people.dogs.deceased')
    - @person.dogs.each do |dog|
      %tr
        %td= link_to dog.id, dog
        %td= dog.registered_name.upcase
        %td= dog.call_name.upcase
        %td= dog.female?? 'F' : 'M'
        %td= dog.registration
        %td= l(dog.whelp_date, :format => :db_people) if dog.litter
        %td YES
        %td= dog.deceased_at

%a{:name => 'litters'}
#litters.subsection
  %h3= t('db.people.litters.header')
  %table
    %tr
      %th= t('db.people.litters.litter_id')
      %th= t('db.people.litters.whelp_date')
      %th= t('db.people.litters.dam_name')
    - @person.litters.each do |litter|
      %td= litter.id
      %td= l(litter.whelp_date, :format => :db_people)
      %td= litter.dam.registered_name

%a{:name => 'clubs'}
#clubs.subsection
  %h3= t('db.people.clubs.header')
  %dl
    %dt BMDCA Member Status
    %dd= @person.bmdca_status
  %table
    %tr
      %th= t('db.people.clubs.name')
    - @person.clubs.each do |club|
      %td= club.name

%a{:name => 'household'}
#household.subsection
  %h3= t('db.people.household.header')
  .detail Multiple people can be linked together into a "household".
  .detail The following people are linked into this household: