config/routes.rb
Bernergarde::Application.routes.draw do
  root :to => 'pages#show', :id => 'home', :format => 'html'

  pages = %w(
    home faq repository repository_p2 trustees operators submit donations
    studies studies_mh studies_broad_institute studies_dm studies_santera
    studies_optigen_pra studies_utrecht_liver_shunt studies_carc
    articles links
  )

  match "/:locale", :to => 'pages#show', :id => 'home', :format => 'html', :via => 'get'
  match "/:locale/:id.:format",
    :id  => /#{pages.join('|')}/,
    :to  => 'pages#show',
    :as  => 'page',
    :via => 'get'

  match "/:locale/db", :to => 'database#index', :as => 'database', :format => 'html', :via => 'get'
  scope "/:locale/db" do
    resources :people, :litters, :dogs, :vets, :reports, :photos do
      collection do
        post :search
      end
    end
  end
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  include AnyMatcher

  belongs_to :owner, :class_name => 'Person'
  belongs_to :litter
  has_many :litters,
           :finder_sql => proc {"SELECT litters.* FROM litters WHERE #{litter_foreign_key}=#{id}"},
           :before_add => :set_litter_parent
  has_many :completed_titles
  has_many :completed_certifications
  has_many :diagnoses

  delegate :breeder, :whelp_date, :sire, :dam, :to => :litter, :allow_nil => true

  def male?
    !self.female?
  end

  def siblings(kind)
    if sire.nil? || dam.nil?
      litters = []
    else
      litters = case kind
                when :full
                  Litter.where(:sire_id => sire, :dam_id => dam)
                when :sire
                  Litter.where(:sire_id => sire).where(['dam_id != ?', dam])
                when :dam
                  Litter.where(:dam_id => dam).where(['sire_id != ?', sire])
                end
    end

    litters.map{|litter| litter.dogs}.flatten
  end

  private

    def litter_foreign_key
      self.female?? 'dam_id' : 'sire_id'
    end

    def set_litter_parent(litter)
      litter.update_attribute(litter_foreign_key, self.id)
    end
end

app/controllers/dogs_controller.rb
class DogsController < DatabaseController
  def index
  end

  def search
    return redirect_to dogs_path unless params[:bg_id].present? || params[:dog].present?

    @dogs = params[:bg_id].present?? Dog.where(:id => params[:bg_id]) : Dog.matching_any(params[:dog])
    if @dogs.empty?
      flash[:error] = t('db.search.dogs.no_results')
      redirect_to dogs_path
    elsif @dogs.size == 1
      redirect_to @dogs.first
    end
  end

  def show
    begin
      @dog = Dog.find(params[:id])
      respond_to do |format|
        format.html
        format.json { render :json => @dog }
      end
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.html { redirect_to :action => :index }
      end
    end
  end
end

app/views/dogs/index.html.haml
%h2= t('db.search.dogs.header')

%p.instructions= t('db.search.dogs.instructions')

%p.help
  %a{:href => '#'}
    %span= t('db.search.dogs.help')

.search_form
  =form_tag(search_dogs_path(I18n.locale)) do
    %fieldset
      =label_tag('dog[registered_name]', t('db.search.dogs.registered_name'))
      =text_field_tag('dog[registered_name]', nil, :size => 40)
      =radio_button_tag('dog[registered_name_match]', 'begins', true)
      %span= t('db.search.begins_with')
      =radio_button_tag('dog[registered_name_match]', 'begins', false)
      %span= t('db.search.contains')

    %fieldset
      =label_tag('dog[call_name]', t('db.search.dogs.call_name'))
      =text_field_tag('dog[call_name]', nil, :size => 15)
      =radio_button_tag('dog[call_name_match]', 'begins', true)
      %span= t('db.search.begins_with')
      =radio_button_tag('dog[call_name_match]', 'begins', false)
      %span= t('db.search.contains')

    %fieldset
      =label_tag('dog[registration_number]', t('db.search.dogs.registration_number'))
      =text_field_tag('dog[registration_number]', nil, :size => 15)
      =radio_button_tag('dog[registration_number_match]', 'begins', true)
      %span= t('db.search.begins_with')
      =radio_button_tag('dog[registration_number_match]', 'begins', false)
      %span= t('db.search.contains')

    %fieldset
      =label_tag('dog[dna_registration_number]', t('db.search.dogs.dna_registration_number'))
      =text_field_tag('dog[dna_registration_number]')
      %span= t('db.search.contains')

    %fieldset
      =label_tag('dog[microchip_number]', t('db.search.dogs.microchip_number'))
      =text_field_tag('dog[microchip_number]')
      %span= t('db.search.contains')

    %fieldset
      =label_tag('dog[breeder_last_name]', t('db.search.dogs.breeder_last_name'))
      =text_field_tag('dog[breeder_last_name]')
      %span= t('db.search.contains')

    %fieldset
      =label_tag('dog[kennel_name]', t('db.search.dogs.kennel_name'))
      =text_field_tag('dog[kennel_name]')
      %span= t('db.search.contains')

    %p= t('db.search.dogs.bgid_prompt')

    %fieldset
      =label_tag('bg_id', t('db.search.dogs.bgid'))
      =text_field_tag('bg_id', nil, :size => 6)

    =submit_tag t('db.search.dogs.submit')

app/views/dogs/search.html.haml
%h1 Berners

This will contain search results soon

app/views/dogs/show.html.haml
%h2= t('db.dog.header')

%dl.overview<
  %dt.name>=          t('db.dog.name')
  %dd>=               @dog.registered_name.upcase
  %dt.bg_id>=         t('db.dog.bg_id')
  %dd>=               @dog.id
  %dt.call_name>=     t('db.dog.call_name')
  %dd>=               @dog.call_name
  %dt.sex>=           t('db.dog.sex')
  %dd>=               sex_info(@dog)
  %dt.registration>=  t('db.dog.registration_number')
  %dd>=               @dog.registration
  %dt.kennel_club>=   t('db.dog.kennel_club')
  %dd>=               t("db.dog.registry.#{@dog.registry.downcase}")
  %dt.registration2>= t('db.dog.registration_number2')
  %dd>=               @dog.registration2
  %dt.kennel_club2>=  t('db.dog.kennel_club2')
  %dd>=               @dog.registry2
  %dt.dna>=           t('db.dog.dna_registration_number')
  %dd>=               @dog.dna_registration
  %dt.whelp_date>=    t('db.dog.whelp_date')
  %dd>=               l(@dog.whelp_date, :format => :db_dog) if @dog.litter
  %dt.litter>=        t('db.dog.litter_id')
  %dd>=               @dog.litter.id if @dog.litter
  %dt.stud_book>=     t('db.dog.stud_book_date')
  %dd>
  %dt.deceased>=      t('db.dog.deceased')
  %dd>
  %dt.death>=         t('db.dog.death_date')
  %dd>
  %dt.data_source>=   t('db.dog.data_source')
  %dd>
  %dt.semen>=         t('db.dog.frozen_semen')
  %dd>
  %dt.rescue>=        t('db.dog.rescue_type')
  %dd>
  %dt.updated>=       t('db.people.last_updated')
  %dd>=               l(@dog.updated_at, :format => :db)

.nav
  %ul
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.people'),    '#people'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.relatives'), '#relatives'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.litters'),   '#litters'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.certs'),     '#certs'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.health'),    '#health'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.physical'),  '#physical'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.studies'),   '#studies'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.titles'),    '#titles'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.photos'),    '#photos'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.pedigree'),  '#pedigree'
    %li{:class => 'subsection_nav'}>= link_to t('db.dog.nav.coi'),       '#coi'

%a{:name => 'people'}
#people.subsection
  %h3= t('db.dog.people.owners')
  %table.owner
    %tr
      %th= t('db.dog.owner.bg_id')
      %th= t('db.dog.owner.name')
      %th= t('db.dog.owner.location')
      %th= t('db.dog.owner.reside')
    %tr
      %td.bgid= link_to @dog.owner.id, @dog.owner
      %td.name= @dog.owner.full_name.upcase
      %td.location= [@dog.owner.city, @dog.owner.state].join(', ').upcase
      %td.reside= t('yes')

  - if @dog.litter
    %h3= t('db.dog.people.breeders')
    %table.breeder
      %tr
        %th= t('db.dog.breeder.bg_id')
        %th= t('db.dog.breeder.name')
        %th= t('db.dog.breeder.location')
      %tr
        %td.bgid= link_to @dog.breeder.id, @dog.breeder
        %td.name= @dog.breeder.full_name.upcase
        %td.location= [@dog.breeder.city, @dog.breeder.state].join(', ').upcase

%a{:name => 'relatives'}
#relatives.subsection
  %h3= t('db.dog.relatives.close.header')
  %h4= t('db.dog.relatives.close.subheader')

  - if @dog.sire
    %table.sire
      %tr
        %th= t('db.dog.relatives.sire.name')
        %th= t('db.dog.relatives.sire.whelp_date')
        %th= t('db.dog.relatives.sire.deceased')
        %th= t('db.dog.relatives.sire.hips')
        %th= t('db.dog.relatives.sire.elbows')
        %th= t('db.dog.relatives.sire.eyes')
        %th= t('db.dog.relatives.sire.heart')
        %th= t('db.dog.relatives.sire.vwd')
        %th= t('db.dog.relatives.sire.dm')
      %tr
        %td= link_to(@dog.sire.registered_name.upcase, @dog.sire)
        %td= l(@dog.sire.whelp_date, :format => :db_dog) if @dog.sire.litter
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>

  - if @dog.dam
    %table.dam
      %tr
        %th= t('db.dog.relatives.dam.name')
        %th= t('db.dog.relatives.dam.whelp_date')
        %th= t('db.dog.relatives.dam.deceased')
        %th= t('db.dog.relatives.dam.hips')
        %th= t('db.dog.relatives.dam.elbows')
        %th= t('db.dog.relatives.dam.eyes')
        %th= t('db.dog.relatives.dam.heart')
        %th= t('db.dog.relatives.dam.vwd')
        %th= t('db.dog.relatives.dam.dm')
      %tr
        %td= link_to(@dog.dam.registered_name.upcase, @dog.dam)
        %td= l(@dog.dam.whelp_date, :format => :db_dog) if @dog.dam.litter
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>

  %h3= t('db.dog.relatives.full_siblings.header')
  %table.siblings
    %tr
      %th= t('db.dog.relatives.full_siblings.name')
      %th= t('db.dog.relatives.full_siblings.whelp_date')
      %th= t('db.dog.relatives.full_siblings.deceased')
      %th= t('db.dog.relatives.full_siblings.hips')
      %th= t('db.dog.relatives.full_siblings.elbows')
      %th= t('db.dog.relatives.full_siblings.eyes')
      %th= t('db.dog.relatives.full_siblings.heart')
      %th= t('db.dog.relatives.full_siblings.vwd')
      %th= t('db.dog.relatives.full_siblings.dm')
    - @dog.siblings(:full).each do |sib|
      %tr
        %td= link_to(sib.registered_name.upcase, sib)
        %td= l(sib.whelp_date, :format => :db_dog) if sib.litter
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>

  %h3= t('db.dog.relatives.half_siblings.sire_header')
  %table.siblings
    %tr
      %th= t('db.dog.relatives.half_siblings.name')
      %th= t('db.dog.relatives.half_siblings.whelp_date')
      %th= t('db.dog.relatives.half_siblings.deceased')
      %th= t('db.dog.relatives.half_siblings.hips')
      %th= t('db.dog.relatives.half_siblings.elbows')
      %th= t('db.dog.relatives.half_siblings.eyes')
      %th= t('db.dog.relatives.half_siblings.heart')
      %th= t('db.dog.relatives.half_siblings.vwd')
      %th= t('db.dog.relatives.half_siblings.dm')
    - @dog.siblings(:sire).each do |sib|
      %tr
        %td= link_to(sib.registered_name.upcase, sib)
        %td= l(sib.whelp_date, :format => :db_dog) if sib.litter
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>

  %h3= t('db.dog.relatives.half_siblings.dam_header')
  %table.siblings
    %tr
      %th= t('db.dog.relatives.half_siblings.name')
      %th= t('db.dog.relatives.half_siblings.whelp_date')
      %th= t('db.dog.relatives.half_siblings.deceased')
      %th= t('db.dog.relatives.half_siblings.hips')
      %th= t('db.dog.relatives.half_siblings.elbows')
      %th= t('db.dog.relatives.half_siblings.eyes')
      %th= t('db.dog.relatives.half_siblings.heart')
      %th= t('db.dog.relatives.half_siblings.vwd')
      %th= t('db.dog.relatives.half_siblings.dm')
    - @dog.siblings(:dam).each do |sib|
      %tr
        %td= link_to(sib.registered_name.upcase, sib)
        %td= l(sib.whelp_date, :format => :db_dog) if sib.litter
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>
        %td>

%a{:name => 'litters'}
#litters.subsection
  I may have litters

%a{:name => 'certs'}
#certs.subsection
  I have certs

%a{:name => 'health'}
#health.subsection
  I have my health

%a{:name => 'physical'}
#physical.subsection
  I have physical attributes and whatnot

%a{:name => 'studies'}
#studies.subsection
  I have studies

%a{:name => 'titles'}
#titles.subsection
  I have titles

%a{:name => 'photos'}
#photos.subsection
  I have a photo

%a{:name => 'pedigree'}
#pedigree.subsection
  I have a pedigree

%a{:name => 'coi'}
#coi.subsection
  I have a coefficient of inbreeding