config/routes.rb
Bernergarde::Application.routes.draw do
  root :to => 'pages#show', :id => 'home', :format => 'html'

  pages = %w(
    home faq repository repository_p2 trustees operators submit donations
    studies studies_mh studies_broad_institute studies_dm studies_santera
    studies_optigen_pra studies_utrecht_liver_shunt studies_carc
    articles links
  )

  match "/:locale", :to => 'pages#show', :id => 'home', :format => 'html', :via => 'get'
  match "/:locale/:id.:format",
    :id  => /#{pages.join('|')}/,
    :to  => 'pages#show',
    :as  => 'page',
    :via => 'get'

  match "/:locale/db", :to => 'database#index', :as => 'database', :format => 'html', :via => 'get'
  scope "/:locale/db" do
    resources :people, :litters, :dogs, :vets, :reports, :photos do
      collection do
        post :search
      end
    end
  end
end

app/controllers/database_controller.rb
class DatabaseController < ApplicationController
  layout 'db'

  def index
  end
end

app/views/database/_nav.html.haml
%ul
  %li= link_to t('db.nav.welcome'), database_path(I18n.locale)
  %li= link_to t('db.nav.people' ), people_path(I18n.locale)
  %li= link_to t('db.nav.litters'), '#'
  %li= link_to t('db.nav.dogs'   ), dogs_path(I18n.locale)
  %li= link_to t('db.nav.vets'   ), '#'
  %li= link_to t('db.nav.reports'), '#'
  %li= link_to t('db.nav.photos' ), '#'
  %li= link_to t('db.nav.submit' ), '#'

app/views/database/index.html.haml
%h2= t('db.welcome.heading')

%p= t('db.welcome.access')

%p= t('db.welcome.help')